name: Update Diagram

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    branches:
      - '**'
      
    inputs:
      tag:
        description: 'Branch or commit tag'     
        required: false
        default: 'master'

jobs:
  Generate:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      
      - name: Visualize
        uses: githubocto/repo-visualizer@0.8.2
        with:
          excluded_paths: "ignore,.github,Client/build/static,DefaultIcons"

      - name: Complete
        run: echo Done!
